### ISSUE TITLE
do two 4xinte32 sorting at the same time

### ISSUE THREAD

**Issue by huaqiangwang** [komrad36/SortingNetworks#1]
as far as I know, there are 2 AVX execution units in latest Broadwell and Skylake platforms, if you duplicate your 128bit AVX version by processing two 4xint32 sorting simultaneously, the performance will double and  
 with no extra running cycles. 
anyway, you have done a great job for sorting.

**Comment by komrad36** [comment]
The platforms do indeed have 256-bit wide YMM registers and corresponding AVX2 instructions that can operate on them in parallel; _however_, any instruction _capable_ of transporting data across lanes, i.e. from one 128-bit half to the other, induces a 3 cycle latency and drastically lowers performance. Scalar methods end up faster in this case.

I covered this in the README:

> These examples can be modified to sort signed or unsigned data as long as the total size of the data is <= 128 bits (16 bytes). Note that trying to use AVX2 to push that to 256 bits will NOT HELP because of the 3 cycle interlane latency that makes shuffling across the 128-bit lane boundary too expensive to be useful.

Thanks!

**Comment by komrad36** [comment]
However if you wanted to do the sorts _independently_, on 4 ints, then certainly, this could potentially improve throughput. Good idea!

**Comment by huaqiangwang** [comment]
What I mean is, the Skylake platform have two 256bit AVX2 unit, each one is capable to process 128/256 SIMD instructions. so, you can do two 128 bit width AVX2 instructions simultaneously. In such a way no cross lane operations required. The test should be quite straightforward.

**Comment by komrad36** [comment]
I see, so loop unrolling. The processor is quite capable of having multiple iterations in flight at the same time, so explicit unrolling may or may not help. The sorting loop should approach 4 muops/cycle in either case.

**Comment by huaqiangwang** [comment]
I agree.

**Comment by komrad36** [comment]
What would be interesting is trying to use 256-bit wide instructions to operate on two whole arrays of 4 integers. That should be doable, I may take a look later.
